# Game settings
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
BACKGROUND_COLOR = (234, 212, 252)
FPS = 60

# Car settings
CAR_IMAGE_PATH = '../assets/car.png'
CAR_WIDTH = 60
CAR_SPEED = 5

# AI settings
POPULATION_SIZE = 50
MUTATION_RATE = 0.1
CROSSOVER_RATE = 0.7
